// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mgcvst_conditional_variance_rows_cpp
Rcpp::NumericMatrix mgcvst_conditional_variance_rows_cpp(const Rcpp::NumericMatrix& A, const Rcpp::List& matrices, int threads, int block_size, bool float32);
RcppExport SEXP _mgcvST_mgcvst_conditional_variance_rows_cpp(SEXP ASEXP, SEXP matricesSEXP, SEXP threadsSEXP, SEXP block_sizeSEXP, SEXP float32SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrices(matricesSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type float32(float32SEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_conditional_variance_rows_cpp(A, matrices, threads, block_size, float32));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_conditional_all_pairs_cpp
Rcpp::IntegerMatrix mgcvst_conditional_all_pairs_cpp(int n);
RcppExport SEXP _mgcvST_mgcvst_conditional_all_pairs_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_conditional_all_pairs_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_conditional_pairs_cpp
Rcpp::List mgcvst_conditional_pairs_cpp(const Rcpp::NumericMatrix& S, const Rcpp::NumericMatrix& V, const Rcpp::IntegerMatrix& pairs);
RcppExport SEXP _mgcvST_mgcvst_conditional_pairs_cpp(SEXP SSEXP, SEXP VSEXP, SEXP pairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type pairs(pairsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_conditional_pairs_cpp(S, V, pairs));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_dense_score_batch_cpp
Rcpp::List mgcvst_dense_score_batch_cpp(const arma::mat& T0, const arma::mat& variance, const arma::mat& error, const arma::vec& scale, const arma::mat& X, const Rcpp::List& nuisance, int threads);
RcppExport SEXP _mgcvST_mgcvst_dense_score_batch_cpp(SEXP T0SEXP, SEXP varianceSEXP, SEXP errorSEXP, SEXP scaleSEXP, SEXP XSEXP, SEXP nuisanceSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type error(errorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type nuisance(nuisanceSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_dense_score_batch_cpp(T0, variance, error, scale, X, nuisance, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_working_state_cpp
Rcpp::List mgcvst_inla_working_state_cpp(const Eigen::MappedSparseMatrix<double>& A, const Eigen::MappedSparseMatrix<double>& X, const Rcpp::NumericMatrix& B, const Rcpp::NumericMatrix& C, const Rcpp::NumericMatrix& O, const Rcpp::IntegerVector& family, const Rcpp::NumericVector& size, const Rcpp::NumericVector& dispersion, int threads);
RcppExport SEXP _mgcvST_mgcvst_inla_working_state_cpp(SEXP ASEXP, SEXP XSEXP, SEXP BSEXP, SEXP CSEXP, SEXP OSEXP, SEXP familySEXP, SEXP sizeSEXP, SEXP dispersionSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type O(OSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_working_state_cpp(A, X, B, C, O, family, size, dispersion, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_compact_units_cpp
Rcpp::List mgcvst_inla_compact_units_cpp(const Eigen::MappedSparseMatrix<double>& A, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::MappedSparseMatrix<double>& X, const Rcpp::NumericMatrix& B, const Rcpp::NumericMatrix& C, const Rcpp::NumericMatrix& O, const Rcpp::IntegerVector& family, const Rcpp::NumericVector& size, const Rcpp::NumericVector& dispersion, const Eigen::Map<Eigen::VectorXd> tau, const Eigen::Map<Eigen::MatrixXd> a, int threads, SEXP prepared, Rcpp::Nullable<Rcpp::NumericMatrix> nuisance_precision);
RcppExport SEXP _mgcvST_mgcvst_inla_compact_units_cpp(SEXP ASEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP XSEXP, SEXP BSEXP, SEXP CSEXP, SEXP OSEXP, SEXP familySEXP, SEXP sizeSEXP, SEXP dispersionSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP threadsSEXP, SEXP preparedSEXP, SEXP nuisance_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type O(OSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type nuisance_precision(nuisance_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_compact_units_cpp(A, Q_map, constraint, X, B, C, O, family, size, dispersion, tau, a, threads, prepared, nuisance_precision));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_fp16_cache_cpp
SEXP mgcvst_fp16_cache_cpp(int n, int r);
RcppExport SEXP _mgcvST_mgcvst_fp16_cache_cpp(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_fp16_cache_cpp(n, r));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_fp16_cache_release_cpp
void mgcvst_fp16_cache_release_cpp(SEXP pointer);
RcppExport SEXP _mgcvST_mgcvst_fp16_cache_release_cpp(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    mgcvst_fp16_cache_release_cpp(pointer);
    return R_NilValue;
END_RCPP
}
// mgcvst_fp16_cache_info_cpp
Rcpp::List mgcvst_fp16_cache_info_cpp(SEXP pointer);
RcppExport SEXP _mgcvST_mgcvst_fp16_cache_info_cpp(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_fp16_cache_info_cpp(pointer));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_fp16_build_cpp
Rcpp::List mgcvst_fp16_build_cpp(SEXP pointer, const Rcpp::IntegerVector& slots, const Eigen::MappedSparseMatrix<double>& A, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::MappedSparseMatrix<double>& X, const Rcpp::NumericMatrix& B, const Rcpp::NumericMatrix& C, const Rcpp::NumericMatrix& O, const Rcpp::IntegerVector& family, const Rcpp::NumericVector& size, const Rcpp::NumericVector& dispersion, const Eigen::Map<Eigen::VectorXd> tau, const Eigen::Map<Eigen::MatrixXd> a, const Eigen::Map<Eigen::MatrixXd> coordinate, const Eigen::Map<Eigen::MatrixXd> basis, double budget, int threads, Rcpp::Nullable<Rcpp::NumericMatrix> nuisance_precision);
RcppExport SEXP _mgcvST_mgcvst_fp16_build_cpp(SEXP pointerSEXP, SEXP slotsSEXP, SEXP ASEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP XSEXP, SEXP BSEXP, SEXP CSEXP, SEXP OSEXP, SEXP familySEXP, SEXP sizeSEXP, SEXP dispersionSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP coordinateSEXP, SEXP basisSEXP, SEXP budgetSEXP, SEXP threadsSEXP, SEXP nuisance_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type slots(slotsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type O(OSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type coordinate(coordinateSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< double >::type budget(budgetSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type nuisance_precision(nuisance_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_fp16_build_cpp(pointer, slots, A, Q_map, constraint, X, B, C, O, family, size, dispersion, tau, a, coordinate, basis, budget, threads, nuisance_precision));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_fp16_write_cpp
void mgcvst_fp16_write_cpp(SEXP pointer, const Rcpp::IntegerVector& slots, const Rcpp::IntegerVector& feature_index, const Rcpp::CharacterVector& feature_id, std::string signature, std::string path);
RcppExport SEXP _mgcvST_mgcvst_fp16_write_cpp(SEXP pointerSEXP, SEXP slotsSEXP, SEXP feature_indexSEXP, SEXP feature_idSEXP, SEXP signatureSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type slots(slotsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type feature_index(feature_indexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type feature_id(feature_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type signature(signatureSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    mgcvst_fp16_write_cpp(pointer, slots, feature_index, feature_id, signature, path);
    return R_NilValue;
END_RCPP
}
// mgcvst_fp16_read_cpp
double mgcvst_fp16_read_cpp(SEXP pointer, const Rcpp::IntegerVector& slots, const Rcpp::IntegerVector& feature_index, const Rcpp::CharacterVector& feature_id, std::string signature, std::string path, double budget);
RcppExport SEXP _mgcvST_mgcvst_fp16_read_cpp(SEXP pointerSEXP, SEXP slotsSEXP, SEXP feature_indexSEXP, SEXP feature_idSEXP, SEXP signatureSEXP, SEXP pathSEXP, SEXP budgetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type slots(slotsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type feature_index(feature_indexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type feature_id(feature_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type signature(signatureSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< double >::type budget(budgetSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_fp16_read_cpp(pointer, slots, feature_index, feature_id, signature, path, budget));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_fp16_pairs_cpp
Rcpp::List mgcvst_fp16_pairs_cpp(SEXP pointer, const Rcpp::IntegerVector& used, int left_first, int left_last, Rcpp::Nullable<Rcpp::IntegerVector> left, Rcpp::Nullable<Rcpp::IntegerVector> right, int threads);
RcppExport SEXP _mgcvST_mgcvst_fp16_pairs_cpp(SEXP pointerSEXP, SEXP usedSEXP, SEXP left_firstSEXP, SEXP left_lastSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type used(usedSEXP);
    Rcpp::traits::input_parameter< int >::type left_first(left_firstSEXP);
    Rcpp::traits::input_parameter< int >::type left_last(left_lastSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type right(rightSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_fp16_pairs_cpp(pointer, used, left_first, left_last, left, right, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_prepare_cpp
SEXP mgcvst_inla_sparse_prepare_cpp(const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_prepare_cpp(SEXP Q_mapSEXP, SEXP constraintSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_prepare_cpp(Q_map, constraint));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_prepared_valid_cpp
bool mgcvst_inla_sparse_prepared_valid_cpp(SEXP prepared);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_prepared_valid_cpp(SEXP preparedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_prepared_valid_cpp(prepared));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_observation_basis_cpp
Rcpp::List mgcvst_inla_sparse_observation_basis_cpp(const Eigen::MappedSparseMatrix<double>& A_map, const Eigen::Map<Eigen::VectorXd> constraint, double coverage, bool full_rank, SEXP prepared);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_observation_basis_cpp(SEXP A_mapSEXP, SEXP constraintSEXP, SEXP coverageSEXP, SEXP full_rankSEXP, SEXP preparedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A_map(A_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< double >::type coverage(coverageSEXP);
    Rcpp::traits::input_parameter< bool >::type full_rank(full_rankSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_observation_basis_cpp(A_map, constraint, coverage, full_rank, prepared));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_batch_cpp
Rcpp::List mgcvst_inla_sparse_batch_cpp(const Eigen::MappedSparseMatrix<double>& A_map, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::MatrixXd> E, const Eigen::Map<Eigen::MatrixXd> D, const Eigen::Map<Eigen::VectorXd> tau, int threads, bool null_target, int block_size, SEXP prepared, Rcpp::Nullable<Rcpp::NumericMatrix> nuisance_precision);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_batch_cpp(SEXP A_mapSEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP XSEXP, SEXP ESEXP, SEXP DSEXP, SEXP tauSEXP, SEXP threadsSEXP, SEXP null_targetSEXP, SEXP block_sizeSEXP, SEXP preparedSEXP, SEXP nuisance_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A_map(A_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type D(DSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type null_target(null_targetSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type nuisance_precision(nuisance_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_batch_cpp(A_map, Q_map, constraint, X, E, D, tau, threads, null_target, block_size, prepared, nuisance_precision));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_materialize_reduced_cpp
Rcpp::List mgcvst_inla_sparse_materialize_reduced_cpp(const Rcpp::List& units, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::Map<Eigen::MatrixXd> coordinate, const Eigen::Map<Eigen::MatrixXd> basis, int threads, SEXP prepared);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_materialize_reduced_cpp(SEXP unitsSEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP coordinateSEXP, SEXP basisSEXP, SEXP threadsSEXP, SEXP preparedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type units(unitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type coordinate(coordinateSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_materialize_reduced_cpp(units, Q_map, constraint, coordinate, basis, threads, prepared));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_materialize_pca_cpp
Rcpp::List mgcvst_inla_sparse_materialize_pca_cpp(const Rcpp::List& units, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::Map<Eigen::MatrixXd> coordinate, const Eigen::Map<Eigen::MatrixXd> basis, Rcpp::Nullable<Rcpp::NumericMatrix> pca_basis, const Rcpp::LogicalVector& pack, int threads, SEXP prepared);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_materialize_pca_cpp(SEXP unitsSEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP coordinateSEXP, SEXP basisSEXP, SEXP pca_basisSEXP, SEXP packSEXP, SEXP threadsSEXP, SEXP preparedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type units(unitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type coordinate(coordinateSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type pca_basis(pca_basisSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type pack(packSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_materialize_pca_cpp(units, Q_map, constraint, coordinate, basis, pca_basis, pack, threads, prepared));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_marginal_liu_moments_cpp
Rcpp::NumericMatrix mgcvst_marginal_liu_moments_cpp(Rcpp::List powers, int threads);
RcppExport SEXP _mgcvST_mgcvst_marginal_liu_moments_cpp(SEXP powersSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type powers(powersSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_marginal_liu_moments_cpp(powers, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_memory_status_cpp
Rcpp::NumericVector mgcvst_memory_status_cpp();
RcppExport SEXP _mgcvST_mgcvst_memory_status_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(mgcvst_memory_status_cpp());
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_liu_logp_cpp
Rcpp::NumericMatrix mgcvst_liu_logp_cpp(const Rcpp::NumericVector& U, const Rcpp::NumericVector& t1, const Rcpp::NumericVector& t2, const Rcpp::NumericVector& t3, const Rcpp::NumericVector& t4, int threads);
RcppExport SEXP _mgcvST_mgcvst_liu_logp_cpp(SEXP USEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP t3SEXP, SEXP t4SEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type U(USEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type t3(t3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type t4(t4SEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_liu_logp_cpp(U, t1, t2, t3, t4, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_pack_cpp
Rcpp::RawVector mgcvst_pca_pack_cpp(const Eigen::Map<Eigen::MatrixXd> M);
RcppExport SEXP _mgcvST_mgcvst_pca_pack_cpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_pack_cpp(M));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_gram_cpp
Rcpp::NumericMatrix mgcvst_pca_gram_cpp(const Rcpp::List& packed, const Rcpp::NumericVector& tau, int threads, int chunk);
RcppExport SEXP _mgcvST_mgcvst_pca_gram_cpp(SEXP packedSEXP, SEXP tauSEXP, SEXP threadsSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_gram_cpp(packed, tau, threads, chunk));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_basis_cpp
Rcpp::NumericMatrix mgcvst_pca_basis_cpp(const Rcpp::List& packed, const Rcpp::NumericVector& tau, const Eigen::Map<Eigen::MatrixXd> R, int threads, int chunk);
RcppExport SEXP _mgcvST_mgcvst_pca_basis_cpp(SEXP packedSEXP, SEXP tauSEXP, SEXP RSEXP, SEXP threadsSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_basis_cpp(packed, tau, R, threads, chunk));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_tables_cpp
Rcpp::List mgcvst_pca_tables_cpp(const Rcpp::NumericMatrix& B, int q, int threads, int block, int tile);
RcppExport SEXP _mgcvST_mgcvst_pca_tables_cpp(SEXP BSEXP, SEXP qSEXP, SEXP threadsSEXP, SEXP blockSEXP, SEXP tileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type block(blockSEXP);
    Rcpp::traits::input_parameter< int >::type tile(tileSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_tables_cpp(B, q, threads, block, tile));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_pairs_cpp
Rcpp::NumericMatrix mgcvst_pca_pairs_cpp(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> C, const Rcpp::List& tables, const Rcpp::IntegerVector& i, const Rcpp::IntegerVector& j, int threads, bool moments);
RcppExport SEXP _mgcvST_mgcvst_pca_pairs_cpp(SEXP ASEXP, SEXP CSEXP, SEXP tablesSEXP, SEXP iSEXP, SEXP jSEXP, SEXP threadsSEXP, SEXP momentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type tables(tablesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type moments(momentsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_pairs_cpp(A, C, tables, i, j, threads, moments));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_pairs_block_cpp
Rcpp::NumericMatrix mgcvst_pca_pairs_block_cpp(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> C, const Rcpp::List& tables, int first, int last, int threads, bool moments, int gene_block, int pair_block);
RcppExport SEXP _mgcvST_mgcvst_pca_pairs_block_cpp(SEXP ASEXP, SEXP CSEXP, SEXP tablesSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP threadsSEXP, SEXP momentsSEXP, SEXP gene_blockSEXP, SEXP pair_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type tables(tablesSEXP);
    Rcpp::traits::input_parameter< int >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type last(lastSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type moments(momentsSEXP);
    Rcpp::traits::input_parameter< int >::type gene_block(gene_blockSEXP);
    Rcpp::traits::input_parameter< int >::type pair_block(pair_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_pairs_block_cpp(A, C, tables, first, last, threads, moments, gene_block, pair_block));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pair_trace_powers_cpp
arma::mat mgcvst_pair_trace_powers_cpp(const Rcpp::List& matrixList, const Rcpp::IntegerMatrix& pairs, int maxPower, int threads);
RcppExport SEXP _mgcvST_mgcvst_pair_trace_powers_cpp(SEXP matrixListSEXP, SEXP pairsSEXP, SEXP maxPowerSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrixList(matrixListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type maxPower(maxPowerSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pair_trace_powers_cpp(matrixList, pairs, maxPower, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mgcvST_mgcvst_conditional_variance_rows_cpp", (DL_FUNC) &_mgcvST_mgcvst_conditional_variance_rows_cpp, 5},
    {"_mgcvST_mgcvst_conditional_all_pairs_cpp", (DL_FUNC) &_mgcvST_mgcvst_conditional_all_pairs_cpp, 1},
    {"_mgcvST_mgcvst_conditional_pairs_cpp", (DL_FUNC) &_mgcvST_mgcvst_conditional_pairs_cpp, 3},
    {"_mgcvST_mgcvst_dense_score_batch_cpp", (DL_FUNC) &_mgcvST_mgcvst_dense_score_batch_cpp, 7},
    {"_mgcvST_mgcvst_inla_working_state_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_working_state_cpp, 9},
    {"_mgcvST_mgcvst_inla_compact_units_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_compact_units_cpp, 15},
    {"_mgcvST_mgcvst_fp16_cache_cpp", (DL_FUNC) &_mgcvST_mgcvst_fp16_cache_cpp, 2},
    {"_mgcvST_mgcvst_fp16_cache_release_cpp", (DL_FUNC) &_mgcvST_mgcvst_fp16_cache_release_cpp, 1},
    {"_mgcvST_mgcvst_fp16_cache_info_cpp", (DL_FUNC) &_mgcvST_mgcvst_fp16_cache_info_cpp, 1},
    {"_mgcvST_mgcvst_fp16_build_cpp", (DL_FUNC) &_mgcvST_mgcvst_fp16_build_cpp, 19},
    {"_mgcvST_mgcvst_fp16_write_cpp", (DL_FUNC) &_mgcvST_mgcvst_fp16_write_cpp, 6},
    {"_mgcvST_mgcvst_fp16_read_cpp", (DL_FUNC) &_mgcvST_mgcvst_fp16_read_cpp, 7},
    {"_mgcvST_mgcvst_fp16_pairs_cpp", (DL_FUNC) &_mgcvST_mgcvst_fp16_pairs_cpp, 7},
    {"_mgcvST_mgcvst_inla_sparse_prepare_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_prepare_cpp, 2},
    {"_mgcvST_mgcvst_inla_sparse_prepared_valid_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_prepared_valid_cpp, 1},
    {"_mgcvST_mgcvst_inla_sparse_observation_basis_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_observation_basis_cpp, 5},
    {"_mgcvST_mgcvst_inla_sparse_batch_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_batch_cpp, 12},
    {"_mgcvST_mgcvst_inla_sparse_materialize_reduced_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_materialize_reduced_cpp, 7},
    {"_mgcvST_mgcvst_inla_sparse_materialize_pca_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_materialize_pca_cpp, 9},
    {"_mgcvST_mgcvst_marginal_liu_moments_cpp", (DL_FUNC) &_mgcvST_mgcvst_marginal_liu_moments_cpp, 2},
    {"_mgcvST_mgcvst_memory_status_cpp", (DL_FUNC) &_mgcvST_mgcvst_memory_status_cpp, 0},
    {"_mgcvST_mgcvst_liu_logp_cpp", (DL_FUNC) &_mgcvST_mgcvst_liu_logp_cpp, 6},
    {"_mgcvST_mgcvst_pca_pack_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_pack_cpp, 1},
    {"_mgcvST_mgcvst_pca_gram_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_gram_cpp, 4},
    {"_mgcvST_mgcvst_pca_basis_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_basis_cpp, 5},
    {"_mgcvST_mgcvst_pca_tables_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_tables_cpp, 5},
    {"_mgcvST_mgcvst_pca_pairs_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_pairs_cpp, 7},
    {"_mgcvST_mgcvst_pca_pairs_block_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_pairs_block_cpp, 9},
    {"_mgcvST_mgcvst_pair_trace_powers_cpp", (DL_FUNC) &_mgcvST_mgcvst_pair_trace_powers_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mgcvST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
