// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mgcvst_pair_trace_powers_cpp
arma::mat mgcvst_pair_trace_powers_cpp(const Rcpp::List& matrixList, const Rcpp::IntegerMatrix& pairs, int maxPower, int threads);
RcppExport SEXP _mgcvST_mgcvst_pair_trace_powers_cpp(SEXP matrixListSEXP, SEXP pairsSEXP, SEXP maxPowerSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrixList(matrixListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type maxPower(maxPowerSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pair_trace_powers_cpp(matrixList, pairs, maxPower, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mgcvST_mgcvst_pair_trace_powers_cpp", (DL_FUNC) &_mgcvST_mgcvst_pair_trace_powers_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mgcvST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
