// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mgcvst_log_adjust_cpp
Rcpp::List mgcvst_log_adjust_cpp(const Rcpp::NumericVector& log_p, const std::string& method);
RcppExport SEXP _mgcvST_mgcvst_log_adjust_cpp(SEXP log_pSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type log_p(log_pSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_log_adjust_cpp(log_p, method));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_dense_score_batch_cpp
Rcpp::List mgcvst_dense_score_batch_cpp(const arma::mat& T0, const arma::mat& variance, const arma::mat& error, const arma::vec& scale, const arma::mat& X, const Rcpp::List& nuisance, int threads, bool score_only);
RcppExport SEXP _mgcvST_mgcvst_dense_score_batch_cpp(SEXP T0SEXP, SEXP varianceSEXP, SEXP errorSEXP, SEXP scaleSEXP, SEXP XSEXP, SEXP nuisanceSEXP, SEXP threadsSEXP, SEXP score_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type error(errorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type nuisance(nuisanceSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type score_only(score_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_dense_score_batch_cpp(T0, variance, error, scale, X, nuisance, threads, score_only));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_prepare_cpp
SEXP mgcvst_inla_sparse_prepare_cpp(const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_prepare_cpp(SEXP Q_mapSEXP, SEXP constraintSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_prepare_cpp(Q_map, constraint));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_prepared_valid_cpp
bool mgcvst_inla_sparse_prepared_valid_cpp(SEXP prepared);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_prepared_valid_cpp(SEXP preparedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_prepared_valid_cpp(prepared));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_observation_basis_cpp
Rcpp::List mgcvst_inla_sparse_observation_basis_cpp(const Eigen::MappedSparseMatrix<double>& A_map, const Eigen::Map<Eigen::VectorXd> constraint, SEXP prepared);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_observation_basis_cpp(SEXP A_mapSEXP, SEXP constraintSEXP, SEXP preparedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A_map(A_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_observation_basis_cpp(A_map, constraint, prepared));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_batch_cpp
Rcpp::List mgcvst_inla_sparse_batch_cpp(const Eigen::MappedSparseMatrix<double>& A_map, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::MatrixXd> E, const Eigen::Map<Eigen::MatrixXd> D, const Eigen::Map<Eigen::VectorXd> tau, int threads, bool null_target, int block_size, SEXP prepared, Rcpp::Nullable<Rcpp::NumericMatrix> nuisance_precision);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_batch_cpp(SEXP A_mapSEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP XSEXP, SEXP ESEXP, SEXP DSEXP, SEXP tauSEXP, SEXP threadsSEXP, SEXP null_targetSEXP, SEXP block_sizeSEXP, SEXP preparedSEXP, SEXP nuisance_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A_map(A_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type D(DSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type null_target(null_targetSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type nuisance_precision(nuisance_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_batch_cpp(A_map, Q_map, constraint, X, E, D, tau, threads, null_target, block_size, prepared, nuisance_precision));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_materialize_reduced_cpp
Rcpp::List mgcvst_inla_sparse_materialize_reduced_cpp(const Rcpp::List& units, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::Map<Eigen::MatrixXd> coordinate, const Eigen::Map<Eigen::MatrixXd> basis, int threads, SEXP prepared);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_materialize_reduced_cpp(SEXP unitsSEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP coordinateSEXP, SEXP basisSEXP, SEXP threadsSEXP, SEXP preparedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type units(unitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type coordinate(coordinateSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_materialize_reduced_cpp(units, Q_map, constraint, coordinate, basis, threads, prepared));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_sparse_materialize_pca_cpp
Rcpp::List mgcvst_inla_sparse_materialize_pca_cpp(const Rcpp::List& units, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::Map<Eigen::MatrixXd> coordinate, const Eigen::Map<Eigen::MatrixXd> basis, Rcpp::Nullable<Rcpp::NumericMatrix> pca_basis, const Rcpp::LogicalVector& pack, int threads, SEXP prepared, Rcpp::Nullable<Rcpp::NumericMatrix> V);
RcppExport SEXP _mgcvST_mgcvst_inla_sparse_materialize_pca_cpp(SEXP unitsSEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP coordinateSEXP, SEXP basisSEXP, SEXP pca_basisSEXP, SEXP packSEXP, SEXP threadsSEXP, SEXP preparedSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type units(unitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type coordinate(coordinateSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type pca_basis(pca_basisSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type pack(packSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_sparse_materialize_pca_cpp(units, Q_map, constraint, coordinate, basis, pca_basis, pack, threads, prepared, V));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_working_state_cpp
Rcpp::List mgcvst_inla_working_state_cpp(const Eigen::MappedSparseMatrix<double>& A, const Eigen::MappedSparseMatrix<double>& X, const Rcpp::NumericMatrix& B, const Rcpp::NumericMatrix& C, const Rcpp::NumericMatrix& O, const Rcpp::IntegerVector& family, const Rcpp::NumericVector& size, const Rcpp::NumericVector& dispersion, int threads);
RcppExport SEXP _mgcvST_mgcvst_inla_working_state_cpp(SEXP ASEXP, SEXP XSEXP, SEXP BSEXP, SEXP CSEXP, SEXP OSEXP, SEXP familySEXP, SEXP sizeSEXP, SEXP dispersionSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type O(OSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_working_state_cpp(A, X, B, C, O, family, size, dispersion, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_inla_compact_units_cpp
Rcpp::List mgcvst_inla_compact_units_cpp(const Eigen::MappedSparseMatrix<double>& A, const Eigen::MappedSparseMatrix<double>& Q_map, const Eigen::Map<Eigen::VectorXd> constraint, const Eigen::MappedSparseMatrix<double>& X, const Rcpp::NumericMatrix& B, const Rcpp::NumericMatrix& C, const Rcpp::NumericMatrix& O, const Rcpp::IntegerVector& family, const Rcpp::NumericVector& size, const Rcpp::NumericVector& dispersion, const Eigen::Map<Eigen::VectorXd> tau, const Eigen::Map<Eigen::MatrixXd> a, int threads, SEXP prepared, Rcpp::Nullable<Rcpp::NumericMatrix> nuisance_precision);
RcppExport SEXP _mgcvST_mgcvst_inla_compact_units_cpp(SEXP ASEXP, SEXP Q_mapSEXP, SEXP constraintSEXP, SEXP XSEXP, SEXP BSEXP, SEXP CSEXP, SEXP OSEXP, SEXP familySEXP, SEXP sizeSEXP, SEXP dispersionSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP threadsSEXP, SEXP preparedSEXP, SEXP nuisance_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Q_map(Q_mapSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type constraint(constraintSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type O(OSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prepared(preparedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type nuisance_precision(nuisance_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_inla_compact_units_cpp(A, Q_map, constraint, X, B, C, O, family, size, dispersion, tau, a, threads, prepared, nuisance_precision));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_memory_status_cpp
Rcpp::NumericVector mgcvst_memory_status_cpp();
RcppExport SEXP _mgcvST_mgcvst_memory_status_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(mgcvst_memory_status_cpp());
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_gram_cpp
Rcpp::NumericMatrix mgcvst_pca_gram_cpp(const Rcpp::List& packed, const Rcpp::NumericVector& tau, int threads, int chunk);
RcppExport SEXP _mgcvST_mgcvst_pca_gram_cpp(SEXP packedSEXP, SEXP tauSEXP, SEXP threadsSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_gram_cpp(packed, tau, threads, chunk));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_basis_cpp
Rcpp::NumericMatrix mgcvst_pca_basis_cpp(const Rcpp::List& packed, const Rcpp::NumericVector& tau, const Eigen::Map<Eigen::MatrixXd> R, int threads, int chunk);
RcppExport SEXP _mgcvST_mgcvst_pca_basis_cpp(SEXP packedSEXP, SEXP tauSEXP, SEXP RSEXP, SEXP threadsSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_basis_cpp(packed, tau, R, threads, chunk));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_tables_cpp
Rcpp::List mgcvst_pca_tables_cpp(const Rcpp::NumericMatrix& B, int q, int threads, int block, int tile);
RcppExport SEXP _mgcvST_mgcvst_pca_tables_cpp(SEXP BSEXP, SEXP qSEXP, SEXP threadsSEXP, SEXP blockSEXP, SEXP tileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type block(blockSEXP);
    Rcpp::traits::input_parameter< int >::type tile(tileSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_tables_cpp(B, q, threads, block, tile));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_monomials_cpp
Rcpp::NumericMatrix mgcvst_pca_monomials_cpp(const Eigen::Map<Eigen::MatrixXd> C);
RcppExport SEXP _mgcvST_mgcvst_pca_monomials_cpp(SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_monomials_cpp(C));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_packed_sum_cpp
Rcpp::NumericMatrix mgcvst_pca_packed_sum_cpp(const Rcpp::List& packed, int q);
RcppExport SEXP _mgcvST_mgcvst_pca_packed_sum_cpp(SEXP packedSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_packed_sum_cpp(packed, q));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_packed_project_cpp
Rcpp::List mgcvst_pca_packed_project_cpp(const Rcpp::List& packed, const Eigen::Map<Eigen::MatrixXd> V, int threads);
RcppExport SEXP _mgcvST_mgcvst_pca_packed_project_cpp(SEXP packedSEXP, SEXP VSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_packed_project_cpp(packed, V, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_dense_cpp
Rcpp::List mgcvst_pca_dense_cpp(const Rcpp::List& H, const Eigen::Map<Eigen::MatrixXd> a, Rcpp::Nullable<Rcpp::NumericMatrix> pca_basis, const Rcpp::LogicalVector& pack, Rcpp::Nullable<Rcpp::NumericMatrix> V, int threads);
RcppExport SEXP _mgcvST_mgcvst_pca_dense_cpp(SEXP HSEXP, SEXP aSEXP, SEXP pca_basisSEXP, SEXP packSEXP, SEXP VSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type pca_basis(pca_basisSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type pack(packSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_dense_cpp(H, a, pca_basis, pack, V, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_spa_pairs_cpp
Rcpp::NumericMatrix mgcvst_pca_spa_pairs_cpp(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> C, const Eigen::Map<Eigen::MatrixXd> K2, const Eigen::Map<Eigen::MatrixXd> T2, const Eigen::Map<Eigen::MatrixXd> R, const Rcpp::NumericVector& scale, const Rcpp::IntegerVector& i, const Rcpp::IntegerVector& j, int threads);
RcppExport SEXP _mgcvST_mgcvst_pca_spa_pairs_cpp(SEXP ASEXP, SEXP CSEXP, SEXP K2SEXP, SEXP T2SEXP, SEXP RSEXP, SEXP scaleSEXP, SEXP iSEXP, SEXP jSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type K2(K2SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_spa_pairs_cpp(A, C, K2, T2, R, scale, i, j, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pca_spa_block_cpp
Rcpp::NumericMatrix mgcvst_pca_spa_block_cpp(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> C, const Eigen::Map<Eigen::MatrixXd> K2, const Eigen::Map<Eigen::MatrixXd> T2, const Eigen::Map<Eigen::MatrixXd> R, const Rcpp::NumericVector& scale, int first, int last, int threads, int gene_block, int pair_block);
RcppExport SEXP _mgcvST_mgcvst_pca_spa_block_cpp(SEXP ASEXP, SEXP CSEXP, SEXP K2SEXP, SEXP T2SEXP, SEXP RSEXP, SEXP scaleSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP threadsSEXP, SEXP gene_blockSEXP, SEXP pair_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type K2(K2SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type last(lastSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type gene_block(gene_blockSEXP);
    Rcpp::traits::input_parameter< int >::type pair_block(pair_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pca_spa_block_cpp(A, C, K2, T2, R, scale, first, last, threads, gene_block, pair_block));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pair_trace_powers_cpp
arma::mat mgcvst_pair_trace_powers_cpp(const Rcpp::List& matrixList, const Rcpp::IntegerMatrix& pairs, int maxPower, int threads);
RcppExport SEXP _mgcvST_mgcvst_pair_trace_powers_cpp(SEXP matrixListSEXP, SEXP pairsSEXP, SEXP maxPowerSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrixList(matrixListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type maxPower(maxPowerSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pair_trace_powers_cpp(matrixList, pairs, maxPower, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pair_basis_sum_cpp
Rcpp::NumericMatrix mgcvst_pair_basis_sum_cpp(const Rcpp::List& H, Rcpp::Nullable<Rcpp::NumericMatrix> init);
RcppExport SEXP _mgcvST_mgcvst_pair_basis_sum_cpp(SEXP HSEXP, SEXP initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type H(HSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type init(initSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pair_basis_sum_cpp(H, init));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pair_basis_cpp
Rcpp::List mgcvst_pair_basis_cpp(const Rcpp::List& H, const Rcpp::NumericMatrix& V, int threads);
RcppExport SEXP _mgcvST_mgcvst_pair_basis_cpp(SEXP HSEXP, SEXP VSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pair_basis_cpp(H, V, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_pair_spa_cpp
Rcpp::List mgcvst_pair_spa_cpp(const Rcpp::List& H, const Rcpp::List& G, const Rcpp::NumericMatrix& a, const Rcpp::IntegerVector& left, const Rcpp::IntegerVector& right, int threads, int order, Rcpp::Nullable<Rcpp::NumericVector> x);
RcppExport SEXP _mgcvST_mgcvst_pair_spa_cpp(SEXP HSEXP, SEXP GSEXP, SEXP aSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP threadsSEXP, SEXP orderSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_pair_spa_cpp(H, G, a, left, right, threads, order, x));
    return rcpp_result_gen;
END_RCPP
}
// mgcvst_spa_cpp
Rcpp::NumericMatrix mgcvst_spa_cpp(const Rcpp::NumericVector& U, const Rcpp::NumericMatrix& S, const Rcpp::NumericMatrix& Tm, int order, int threads);
RcppExport SEXP _mgcvST_mgcvst_spa_cpp(SEXP USEXP, SEXP SSEXP, SEXP TmSEXP, SEXP orderSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type U(USEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcvst_spa_cpp(U, S, Tm, order, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mgcvST_mgcvst_log_adjust_cpp", (DL_FUNC) &_mgcvST_mgcvst_log_adjust_cpp, 2},
    {"_mgcvST_mgcvst_dense_score_batch_cpp", (DL_FUNC) &_mgcvST_mgcvst_dense_score_batch_cpp, 8},
    {"_mgcvST_mgcvst_inla_sparse_prepare_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_prepare_cpp, 2},
    {"_mgcvST_mgcvst_inla_sparse_prepared_valid_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_prepared_valid_cpp, 1},
    {"_mgcvST_mgcvst_inla_sparse_observation_basis_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_observation_basis_cpp, 3},
    {"_mgcvST_mgcvst_inla_sparse_batch_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_batch_cpp, 12},
    {"_mgcvST_mgcvst_inla_sparse_materialize_reduced_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_materialize_reduced_cpp, 7},
    {"_mgcvST_mgcvst_inla_sparse_materialize_pca_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_sparse_materialize_pca_cpp, 10},
    {"_mgcvST_mgcvst_inla_working_state_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_working_state_cpp, 9},
    {"_mgcvST_mgcvst_inla_compact_units_cpp", (DL_FUNC) &_mgcvST_mgcvst_inla_compact_units_cpp, 15},
    {"_mgcvST_mgcvst_memory_status_cpp", (DL_FUNC) &_mgcvST_mgcvst_memory_status_cpp, 0},
    {"_mgcvST_mgcvst_pca_gram_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_gram_cpp, 4},
    {"_mgcvST_mgcvst_pca_basis_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_basis_cpp, 5},
    {"_mgcvST_mgcvst_pca_tables_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_tables_cpp, 5},
    {"_mgcvST_mgcvst_pca_monomials_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_monomials_cpp, 1},
    {"_mgcvST_mgcvst_pca_packed_sum_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_packed_sum_cpp, 2},
    {"_mgcvST_mgcvst_pca_packed_project_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_packed_project_cpp, 3},
    {"_mgcvST_mgcvst_pca_dense_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_dense_cpp, 6},
    {"_mgcvST_mgcvst_pca_spa_pairs_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_spa_pairs_cpp, 9},
    {"_mgcvST_mgcvst_pca_spa_block_cpp", (DL_FUNC) &_mgcvST_mgcvst_pca_spa_block_cpp, 11},
    {"_mgcvST_mgcvst_pair_trace_powers_cpp", (DL_FUNC) &_mgcvST_mgcvst_pair_trace_powers_cpp, 4},
    {"_mgcvST_mgcvst_pair_basis_sum_cpp", (DL_FUNC) &_mgcvST_mgcvst_pair_basis_sum_cpp, 2},
    {"_mgcvST_mgcvst_pair_basis_cpp", (DL_FUNC) &_mgcvST_mgcvst_pair_basis_cpp, 3},
    {"_mgcvST_mgcvst_pair_spa_cpp", (DL_FUNC) &_mgcvST_mgcvst_pair_spa_cpp, 8},
    {"_mgcvST_mgcvst_spa_cpp", (DL_FUNC) &_mgcvST_mgcvst_spa_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_mgcvST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
