# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mgcvst_conditional_variance_rows_cpp <- function(A, matrices, threads = 1L, block_size = 512L, float32 = FALSE) {
    .Call(`_mgcvST_mgcvst_conditional_variance_rows_cpp`, A, matrices, threads, block_size, float32)
}

mgcvst_conditional_all_pairs_cpp <- function(n) {
    .Call(`_mgcvST_mgcvst_conditional_all_pairs_cpp`, n)
}

mgcvst_conditional_pairs_cpp <- function(S, V, pairs) {
    .Call(`_mgcvST_mgcvst_conditional_pairs_cpp`, S, V, pairs)
}

mgcvst_dense_score_batch_cpp <- function(T0, variance, error, scale, X, nuisance, threads = 1L) {
    .Call(`_mgcvST_mgcvst_dense_score_batch_cpp`, T0, variance, error, scale, X, nuisance, threads)
}

mgcvst_inla_sparse_prepare_cpp <- function(Q_map, constraint) {
    .Call(`_mgcvST_mgcvst_inla_sparse_prepare_cpp`, Q_map, constraint)
}

mgcvst_inla_sparse_prepared_valid_cpp <- function(prepared) {
    .Call(`_mgcvST_mgcvst_inla_sparse_prepared_valid_cpp`, prepared)
}

mgcvst_inla_sparse_observation_basis_cpp <- function(A_map, constraint, coverage = 0.995, full_rank = FALSE, prepared = NULL) {
    .Call(`_mgcvST_mgcvst_inla_sparse_observation_basis_cpp`, A_map, constraint, coverage, full_rank, prepared)
}

mgcvst_inla_sparse_batch_cpp <- function(A_map, Q_map, constraint, X, E, D, tau, threads = 1L, score_only = FALSE, null_target = FALSE, block_size = 32L, prepared = NULL, unit_only = FALSE, nuisance_precision = NULL) {
    .Call(`_mgcvST_mgcvst_inla_sparse_batch_cpp`, A_map, Q_map, constraint, X, E, D, tau, threads, score_only, null_target, block_size, prepared, unit_only, nuisance_precision)
}

mgcvst_inla_sparse_units_cpp <- function(A, Q, constraint, X, E, D, tau, threads = 1L, prepared = NULL, nuisance_precision = NULL) {
    .Call(`_mgcvST_mgcvst_inla_sparse_units_cpp`, A, Q, constraint, X, E, D, tau, threads, prepared, nuisance_precision)
}

mgcvst_inla_sparse_materialize_cpp <- function(units, Q_map, constraint, threads = 1L, prepared = NULL, block_size = 32L) {
    .Call(`_mgcvST_mgcvst_inla_sparse_materialize_cpp`, units, Q_map, constraint, threads, prepared, block_size)
}

mgcvst_inla_sparse_materialize_reduced_cpp <- function(units, Q_map, constraint, coordinate, basis, threads = 1L, prepared = NULL) {
    .Call(`_mgcvST_mgcvst_inla_sparse_materialize_reduced_cpp`, units, Q_map, constraint, coordinate, basis, threads, prepared)
}

mgcvst_state_write_cpp <- function(path, signature, feature_id, a, M, width, error = "") {
    invisible(.Call(`_mgcvST_mgcvst_state_write_cpp`, path, signature, feature_id, a, M, width, error))
}

mgcvst_state_read_cpp <- function(path, signature, feature_id) {
    .Call(`_mgcvST_mgcvst_state_read_cpp`, path, signature, feature_id)
}

mgcvst_landmark_stream_cpp <- function(paths, feature_ids, state_signature, references, output_paths, summary_signature, threads = 1L) {
    .Call(`_mgcvST_mgcvst_landmark_stream_cpp`, paths, feature_ids, state_signature, references, output_paths, summary_signature, threads)
}

mgcvst_trace_read_cpp <- function(path, signature, feature_id, n_ref) {
    .Call(`_mgcvST_mgcvst_trace_read_cpp`, path, signature, feature_id, n_ref)
}

mgcvst_marginal_liu_moments_cpp <- function(powers, threads = 1L) {
    .Call(`_mgcvST_mgcvst_marginal_liu_moments_cpp`, powers, threads)
}

mgcvst_memory_status_cpp <- function() {
    .Call(`_mgcvST_mgcvst_memory_status_cpp`)
}

mgcvst_pair_trace_powers_cpp <- function(matrixList, pairs, maxPower = 4L, threads = 1L) {
    .Call(`_mgcvST_mgcvst_pair_trace_powers_cpp`, matrixList, pairs, maxPower, threads)
}

mgcvst_pair_lowrank_cpp <- function(A, left, right, scale, pairs, threads = 1L) {
    .Call(`_mgcvST_mgcvst_pair_lowrank_cpp`, A, left, right, scale, pairs, threads)
}

mgcvst_landmark_trace_cpp <- function(matrixList, referenceList, threads = 1L, float32 = TRUE) {
    .Call(`_mgcvST_mgcvst_landmark_trace_cpp`, matrixList, referenceList, threads, float32)
}

