# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mgcvst_marginal_liu_moments_cpp <- function(powers, threads = 1L) {
    .Call(`_mgcvST_mgcvst_marginal_liu_moments_cpp`, powers, threads)
}

mgcvst_pair_trace_powers_cpp <- function(matrixList, pairs, maxPower = 4L, threads = 1L) {
    .Call(`_mgcvST_mgcvst_pair_trace_powers_cpp`, matrixList, pairs, maxPower, threads)
}

